CREATE TABLE dogs  (ID INT NOT NULL AUTO_INCREMENT,
		    name VARCHAR(15) NOT NULL,
		    breed VARCHAR(15) NOT NULL,
		    age INT NOT NULL,
		    description TEXT,
		    colour NOT NULL,
		    dateRegistered TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		    avatarURL VARCHAR(64),
		    shelter VARCHAR(64) NOT NULL,
		    PRIMARY KEY (ID),
		    FOREIGN KEY (shelter) REFERENCES shelters (location));