CREATE TABLE chat (ID INT NOT NULL AUTO_INCREMENT,
		   user1 INT,
		   user2 INT,
		   PRIMARY KEY (ID),
		   FOREIGN KEY (user1) REFERENCES users (ID),
		   FOREIGN KEY (user2) REFERENCES users (ID));