CREATE TABLE dogs  (ID INT NOT NULL AUTO_INCREMENT,
			shelter INT,
		    name VARCHAR(24) NOT NULL,
		    breed VARCHAR(24) NOT NULL,
		    age INT NOT NULL,
		    description TEXT,
		    colour VARCHAR(24) NOT NULL,
		    dateRegistered TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		    avatarURL VARCHAR(64),
		    PRIMARY KEY (ID),
		    FOREIGN KEY (shelter) REFERENCES shelters (ID));